"""Data models for Steam API."""

# Base models
from .base import ErrorResponse, PaginatedResponse, SteamModel, SteamResponse

# Family models
from .family import (
    EFamilyGroupRole,
    EPurchaseRequestAction,
    FamilyGroup,
    FamilyGroupFormerMember,
    FamilyGroupMember,
    FamilyGroupPendingInvite,
    FamilyGroupPendingInviteForUser,
    FamilyGroupStatus,
    FamilyGroupStatusResponse,
    MembershipHistoryEntry,
    PlaytimeEntry,
    PlaytimeSummary,
    PlaytimeSummaryResponse,
    SharedLibraryApp,
    SharedLibraryAppsData,
    SharedLibraryAppsResponse,
)

# Game models
from .game import (
    Achievement,
    AppDetails,
    AppListResponse,
    GameSchema,
    GameSchemaResponse,
    GameStat,
    GetAppListResponse,
    GetOwnedGamesResponse,
    GetPlayerAchievementsResponse,
    GetSchemaResponse,
    GetUserStatsResponse,
    OwnedGame,
    OwnedGamesResponse,
    PlayerAchievementsResponse,
    SchemaAchievement,
    SchemaStat,
    SteamApp,
    UserStatsResponse,
)

# Market models
from .market import (
    InventoryItem,
    InventoryResponse,
    ItemDescription,
    ItemPriceResponse,
    MarketHistoryEntry,
    MarketHistoryResponse,
    MarketItem,
    MarketListing,
    MarketListingsResponse,
    MarketSearch,
    MarketSearchResponse,
    PriceInfo,
)

# Player models
from .player import (
    CommunityVisibilityState,
    Friend,
    FriendsListResponse,
    PersonaState,
    PlayerBan,
    PlayerBansResponse,
    PlayerSummariesResponse,
    PlayerSummary,
    ResolveVanityURLResponse,
    VanityURLResolution,
)

# Stats models
from .stats import (
    GetGlobalAchievementResponse,
    GetGlobalStatsResponse,
    GetNewsResponse,
    GetPlayerCountResponse,
    GetUserStatsGameResponse,
    GlobalAchievementResponse,
    GlobalAchievementStat,
    GlobalStat,
    GlobalStatsResponse,
    LeaderboardEntry,
    LeaderboardResponse,
    NewsItem,
    NewsResponse,
    PlayerCount,
    PlayerCountResponse,
    UserAchievement,
    UserStat,
)
from .stats import (
    UserStatsResponse as StatsUserStatsResponse,
)

__all__ = [
    "Achievement",
    "AppDetails",
    "AppListResponse",
    "CommunityVisibilityState",
    "EFamilyGroupRole",
    "EPurchaseRequestAction",
    "ErrorResponse",
    "FamilyGroup",
    "FamilyGroupFormerMember",
    "FamilyGroupMember",
    "FamilyGroupPendingInvite",
    "FamilyGroupPendingInviteForUser",
    "FamilyGroupStatus",
    "FamilyGroupStatusResponse",
    "Friend",
    "FriendsListResponse",
    "GameSchema",
    "GameSchemaResponse",
    "GameStat",
    "GetAppListResponse",
    "GetGlobalAchievementResponse",
    "GetGlobalStatsResponse",
    "GetNewsResponse",
    "GetOwnedGamesResponse",
    "GetPlayerAchievementsResponse",
    "GetPlayerCountResponse",
    "GetSchemaResponse",
    "GetUserStatsGameResponse",
    "GetUserStatsResponse",
    "GlobalAchievementResponse",
    "GlobalAchievementStat",
    "GlobalStat",
    "GlobalStatsResponse",
    "InventoryItem",
    "InventoryResponse",
    "ItemDescription",
    "ItemPriceResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "MarketHistoryEntry",
    "MarketHistoryResponse",
    "MarketItem",
    "MarketListing",
    "MarketListingsResponse",
    "MarketSearch",
    "MarketSearchResponse",
    "MembershipHistoryEntry",
    "NewsItem",
    "NewsResponse",
    "OwnedGame",
    "OwnedGamesResponse",
    "PaginatedResponse",
    "PersonaState",
    "PlayerAchievementsResponse",
    "PlayerBan",
    "PlayerBansResponse",
    "PlayerCount",
    "PlayerCountResponse",
    "PlayerSummariesResponse",
    "PlayerSummary",
    "PlaytimeEntry",
    "PlaytimeSummary",
    "PlaytimeSummaryResponse",
    "PriceInfo",
    "ResolveVanityURLResponse",
    "SchemaAchievement",
    "SchemaStat",
    "SharedLibraryApp",
    "SharedLibraryAppsData",
    "SharedLibraryAppsResponse",
    "StatsUserStatsResponse",
    "SteamApp",
    "SteamModel",
    "SteamResponse",
    "UserAchievement",
    "UserStat",
    "UserStatsResponse",
    "VanityURLResolution",
]
